use stock;
INSERT INTO brand(name, description)
VALUES('nike', 'nike brand description');
INSERT INTO brand(name, description)
VALUES('adidas', 'adidas brand description');
INSERT INTO brand(name, description)
VALUES('puma', 'puma brand description');
INSERT INTO brand(name, description)
VALUES('lego', 'lego brand description');
INSERT INTO brand(name, description)
VALUES('mattel', 'mattel brand description');
INSERT INTO brand(name, description)
VALUES('hasbro', 'hasbro brand description');
INSERT INTO category(name, description)
VALUES('category1', 'category1 category description');
INSERT INTO category(name, description)
VALUES('category2', 'category2 category description');
INSERT INTO category(name, description)
VALUES('category3', 'category3 category description');
INSERT INTO category(name, description)
VALUES('category4', 'category4 category description');
INSERT INTO category(name, description)
VALUES('category5', 'category5 category description');
INSERT INTO category(name, description)
VALUES('category6', 'category6 category description');
INSERT INTO category(name, description)
VALUES('category7', 'category7 category description');
INSERT INTO category(name, description)
VALUES('category8', 'category8 category description');
INSERT INTO category(name, description)
VALUES('category9', 'category9 category description');
